### ISSUE TITLE
DAC (PCM Sample) support

### ISSUE THREAD

**Issue by LoveBodhi** [Wohlstand/libOPNMIDI#103]
Originally, Yamaha YM2612 have PCM Sample Support (Called DAC), but in this lib, no DAC support, I feel bored......

**Comment by LoveBodhi** [comment]
Error: Duplicated issue

**Comment by Wohlstand** [comment]
Yeah, I already has this https://github.com/Wohlstand/libOPNMIDI/issues/5 for planning and discussion of the thing. Right now, I need to solve challenges of WOPLv3 format that will allow storing of PCM samples and allow usage of DAC.
