### ISSUE TITLE
[Question] How does CC74 affect 4-op instruments with chained modulators

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libOPNMIDI#111]
For instruments using alg 4,5,6, it's clear. But what about, for example, alg 0, which goes like 1->2->3->4 ?
It affects only OP1, or all modulator operators?

**Comment by Wohlstand** [comment]
Right now it affects modulators only, however, I do think to add the option to choose which operators should be affected by CC74 as there are a lot of instruments that would work better if you're able to set up this behavior
