### ISSUE TITLE
[Feature Request] Add ability to mute MIDI channels

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libOPNMIDI#112]
this one would be mostly useful for MID2VGM utility - since VGM format has a limit of 2 chips, only 12 FM channels can be used at once. With most MIDIs it's not enough. If there was an argument like `--mute 5 8 14` (meaning mute MIDI channels 5, 8 and 14, which are, for example, the least important and audible) it would improve the functionality of this tool, without resorting to MIDI file editing.

**Comment by Wohlstand** [comment]
Good idea, the channel muting is already exist at backend of the MIDI sequencer here, can be utilized very quickly :fox_face:

**Comment by Wohlstand** [comment]
As I said, the backend was already done, so, feel free to test, there is the next argument added:
```
-mc <x y z ...>
```
or it's alias `--mute-channels`

**Comment by freq-mod** [comment]
From what i managed to test, it looks like it works correctly, thanks!

P.S. for some reason, the VGM (or VGZ, at least) files outputted by mid2vgm are played off pitch in PGEMusplay, significantly higher than they should

**Comment by Wohlstand** [comment]
> .S. for some reason, the VGM (or VGZ, at least) files outputted by mid2vgm are played off pitch in PGEMusplay, significantly higher than they should

That directly depends on which bank you had to select, resulted VGM/VGZ file is the capture of the same output as generated to play on emulated chips by regular way.

**Comment by freq-mod** [comment]
I know, they sound higher in pitch than the MIDI files played using the same FM bank

**Comment by freq-mod** [comment]
Still, it's the problem of PGEmusplay, on ZXTune they sound fine

**Comment by Wohlstand** [comment]
Can you send me an example file and a bank? The thing sounds REALLY strange and mysterious... Moondust MusPlay does use the GME as a core that plays VGM/VGZ.

**Comment by freq-mod** [comment]
[vgmbug.zip](https://github.com/Wohlstand/libOPNMIDI/files/7466685/vgmbug.zip)

**Comment by Wohlstand** [comment]
Ooooke, seems that because the bank uses OPNA model, and I bet, there is a mistake against the clock value at VGM file itself, causing the difference: I reproduced the bug with a bank using your bank:

[demo.zip](https://github.com/Wohlstand/libOPNMIDI/files/7466751/demo.zip)

**Comment by freq-mod** [comment]
GME in general is petty meh, i stumbled upon one YM2151 vgm song that PGE Musplay refuses to play... libvgm would be a better solution IMO

**Comment by Wohlstand** [comment]
I checked some, the bug happens when using MAME emulator (can be switched by compile time only), and doesn't happen with Nuked and GENS. I guess, here is some small hidden mistake appears, should be easily to fix.

**Comment by Wohlstand** [comment]
Fixed that, the bug was very small, now works fine, in next update will work fine.
