### ISSUE TITLE
Upgrade current MAME cores to MAME ymfm BSD cores

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libOPNMIDI#114]
They are much more accurate(SSG-EG), lightweight (most mobile can handle at least few of them) and stable, while being actively supported.

**Comment by Wohlstand** [comment]
Their problem is they are require C++17, that kills the main idea of general compatibility of the library including old compilers. But I know about them and I trying to find the compromise against using of them. Possibly, I'll use old MAME cores if compiler is not suitable to build them.

**Comment by Wohlstand** [comment]
I forgot to tell that the BSD-licensed thing called YMFM had bee added already as a separated core. I replaced the Genesis Plus GX and PMDWin emulators as they was being worst among others. The YMFM is available for only compilers are do support C++14 (via CMake configure or by manual Macro definitions). And if C++14 is unavailable, then YMFM support will not being built.
