### ISSUE TITLE
how to port this to golang

### ISSUE THREAD

**Issue by Mike77154** [Wohlstand/libOPNMIDI#118]
the idea is using a extension of this code in a engine called Ikemen https://github.com/ikemen-engine/Ikemen-GO for having more onboard synths with the soundfont player

**Comment by Wohlstand** [comment]
No need, if you want to use it in Go, it's easy use via C-ABI, Go is able to use any library via C-ABI.

**Comment by Wohlstand** [comment]
I think, I have some Go example on my end, I need to find the code at my archive... If I find it, I'll add it into examples directory, so, you can see how to use the library from the Golang.

**Comment by Wohlstand** [comment]
Just now I sent the simple example how to use the library in the Golang: https://github.com/Wohlstand/libOPNMIDI/commit/e9859ded45294bd8d4eb7d4a4443f8c2982289bd

**Comment by Wohlstand** [comment]
Closed because of no response for a long time.
