### ISSUE TITLE
Writing unit test with catch framework

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libOPNMIDI#19]
I want to create unit tests for RT structures. User map, among things.
Catch framework is difficult to work with because it a condensation of a lot of code in headers, requires lots of RAM.

Fortunately a person made very recently a minimal version for simple usage. [link](https://www.reddit.com/r/cpp/comments/8dgyqb/catchmini_catch_subset_in_less_than_300_lines_of/)
Do you mind switching to this version? After quick testing, RAM needs went down by 80%.

**Comment by Wohlstand** [comment]
I think, that would be useful, let's keep both versions, but use mainly this, I'll put the header as `catchmini.hpp`

**Comment by jpcima** [comment]
The mini version has two appreciable qualities from my side of things. 1) build faster 2) does not crash the computer by filling up memory.

After looking at the implemention of catch, I came to the conclusion there isn't possibility for separate compilation.
The build tries to do all interprocedural optimizations and inlining, and just takes a lot of resources; to finish with a program of 5 times the size.

**Comment by Wohlstand** [comment]
On memory overflow my computer gets be crazy: it goes to freeze EVERYTHING and does HARD write of swap, I hate this... and I hate "modern" software which uses lots of memory for nothing...

**Comment by jpcima** [comment]
Yeah.. Maybe you know, but in linux you can enable a shortcut to invoke the oom killer, and get a chance to save your system if a crash is coming. (sysrq keys)

If I could do one thing to make computing better at a finger snap... Remove all Javascript. :smile:

**Comment by Wohlstand** [comment]
> Yeah.. Maybe you know, but in linux you can enable a shortcut to invoke the oom killer, and get a chance to save your system if a crash is coming. (sysrq keys)

Yeah, OOM Killer is that I needed, and yeah I better to crash a jerk-process than freeze the entire system :fox_face: 

> If I could do one thing to make computing better at a finger snap... Remove all Javascript. smile

That is totally right! :laughing:

**Comment by Wohlstand** [comment]
I see you have closed it, because of build fail on Catch's CI...
And I see some of macOS builds are was failed:
https://travis-ci.org/catchorg/Catch2/builds/370003489

**Comment by Wohlstand** [comment]
Oops :grin:,  I had to press a wrong button...
I don't want close this as issue is not completed

**Comment by Wohlstand** [comment]
Closed as abandoned.
