### ISSUE TITLE
Implement a note length expander for real-time API

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#46]
Yet another playback issue.
On some occassions, drums will play incorrectly - they will be distorted, cut, etc. Affects both of our banks, but what's really weird it seems to affect only VLC plugin (WTF?), as command line ultility has no problem with it (not 100% sure though)
[corruptdrums.zip](https://github.com/Wohlstand/libOPNMIDI/files/2138509/corruptdrums.zip) - MIDI examples and recordings 

p.s. happens witth ADLMIDI as well (tested on embedded DMXOPL bank #72)

**Comment by Wohlstand** [comment]
I guess, It's because of too short notes. Built-in MIDI sequencer does automatic fix of those long notes, however, for real-time I will need to make some small tweak, and yeah, it's possible.

**Comment by Wohlstand** [comment]
All drums in those MIDI files are having zero length. As I told, built-in MIDI player does auto-expanding of too short drum notes.

**Comment by Wohlstand** [comment]
The VLC plugin uses real-time API which is off built-in MIDI player. It's needed a different strategy to resolve this drums shit also on real-time too.

**Comment by papiezak** [comment]
Don't know whether I should write about this here or Wohlstand/libADLMIDI#38 but it looks like emulator selector is broken - I can have 49 Nuked cores, at 50 sound cuts to silence after 2 seconds (unrealistic, isn't it?). I don't hear any difference between emus as SSG-EG based instruments play correctly even on "Gens 2.10".
But at least count of emulated chips appear to work - at single chip notes are cutting like crazy.

**Comment by Wohlstand** [comment]
> I can have 49 Nuked cores, at 50 sound cuts to silence after 2 seconds (unrealistic, isn't it?)

It's yeah, on my computer Nuked OPN2 is able to work right with up to 3 cores, however from GZDoom it works with 8 cores, BUT, gives some second delay until it will begin playing (on other emulators, it works instant).

> I don't hear any difference between emus as SSG-EG based instruments play correctly even on "Gens 2.10".

I'll check this...

> But at least count of emulated chips appear to work - at single chip notes are cutting like crazy.

It's arpeggio thing that tries to unite multiple channels into one, and every tick it sequentially swaps each note who will use this channel on this tick.

**Comment by Wohlstand** [comment]
At me emulator switch WORKS, just now I have checked "bird-tweet" which uses SSG-EG, and behavior is different on MAME and on GENS. Also, it is "Genesis Plus GX" must be, but it has been disabled by default due unresolved trouble with missing notes on it...

**Comment by papiezak** [comment]
Weird. Can you please give me .mid which has bird tweet or telephone instrument?

**Comment by Wohlstand** [comment]
It's my full set of test MIDI files I have at me:
[MIDITEST.zip](https://github.com/Wohlstand/libOPNMIDI/files/2142162/MIDITEST.zip)

**Comment by jpcima** [comment]
I started a work on data structures we discussed about, which permits to facilitate note tracking, while operating in RT constraints.
https://github.com/jpcima/libADLMIDI/tree/std-structures

**Comment by papiezak** [comment]
@Wohlstand please ping.
The bug's still here, and since way too many .MIDs had near zero length drums, like 2/3 of my MIDI collection suffer from that. With vlc, it's hard to test/degug DMXOPN2 drums, and on some MIDIs, the percussion track is almost gone:
https://instaud.io/3das - as played using vlc real-time MIDI plugin
https://instaud.io/3dat - as played using PGE MUSplay

**Comment by Wohlstand** [comment]
@papiezak , Thanks for reminding, yeah, @jpcima have made everything necessary, I have just forgot by busing on different things... I think, it's not a hard deal to implement, will try this sooner...

**Comment by Wohlstand** [comment]
@papiezak , @jpcima  have implemented this feature on the side of RealTime module, therefore it's no more issue on the side of real-time synthesizers and VLC plugin!
https://github.com/Wohlstand/libOPNMIDI/pull/78

**Comment by Wohlstand** [comment]
Please confirum it's fine in both libOPNMIDI and libADLMIDI. Also, I have made the "Enable this synthesizer" flag in VLC setup to allow easier switch between plugins out of VLC's functionality which doesn't allows choose one of codecs of same yet.

**Comment by papiezak** [comment]
I know. Testing it right now, at this moment I can tell sounds at least much better.

**Comment by papiezak** [comment]
Looks like it's fine now. I tested as much as I could, thanks a ton!
