### ISSUE TITLE
Percussion instruments can be cut (channel management issue?)

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#64]
This weird crap affects very few .mids, but it's kinda annoying.
Take a random .midi file that's affected -  [lel.zip](https://github.com/Wohlstand/libOPNMIDI/files/2402287/lel.zip); near 6 seconds mark Gated SD goes silent, I can hear only closed hi-hat that plays in background (recording - https://instaud.io/2HHa)
Then I muted every melodic instrument in this song _by firing up bank editor and setting TL values of every instrument to 127_  - surprise, drums are alright now! (https://instaud.io/2HHc)
At this point I raised a volume of melodics a bit - snare disappeared again (https://instaud.io/2HHe)

Tested only with my own bank, since yours XG one doesn't have a power drumkit.
Attached zip has all three bank variants I used to "analyze" the issue.

**Comment by Wohlstand** [comment]
Or, looks, the bank needs the save with full re-calculation of sound delays, try that..

**Comment by papiezak** [comment]
> the bank needs the save with full re-calculation of sound delays, try that.<

Didn't help.

>instruments are has no proper releasing and there are designed to be held longer

Which? Gated SD has release rate=6, it is enough

**Comment by papiezak** [comment]
Hmmm... removed SSG-EG flag from Gated SD and it plays now when melodics aren't muted.
Weird.

**Comment by Wohlstand** [comment]
Yesterday I did the big update of channels management where I have resolved lot of various issues, please test the stuff, is it better now?

**Comment by papiezak** [comment]
I guess so. On my side, I made several tweaks to my bank (release rates, some volumes), so I don't hear anythink suspicious.

P.S. "DMXOPN2" that is in `fm_banks` directory is severely outdated - you may want to update it - [YM2612.zip](https://github.com/Wohlstand/libOPNMIDI/files/2420006/YM2612.zip), maaany SC-88 sounds were implemented, existing sound were improved and there's even partial support for GS way of changing synthesizer mode (hope it's working though)

**Comment by sneakernets** [comment]
Yeah, 
@papiezak feel free to send a pull request on that, I'm going to be working on that soon now that things have settled down IRL
