### ISSUE TITLE
Try a newer Gens emulator

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libOPNMIDI#65]
Hi. In this work branch is the updated emulator of the fork Gens/GS II. Please try it.
https://github.com/jpcima/libOPNMIDI/tree/gens-gs-ii

Not done currently: integration of DAC and timer logic, which Gens has tied in emulation to VDP update periods.

**Comment by jpcima** [comment]
So, I ran both the Gens versions vs other emulators on signal analyzer.
I played a long release sound Tubular Bells, I compared some results side by side.

Old vs New => no difference on release time
The longer envelope of all is Nuked, second was MAME and Gens was shortest.

**Comment by Wohlstand** [comment]
Anyway, once I tried to play Asterix game in latest GENS emulator, looks like it has better SSG-EG support, so, it's a reason to upgrade emulator even it's not so better than it's old version.

**Comment by Wohlstand** [comment]
Closed because the newer GENS emulator is already in use for a while. Completed!
