### ISSUE TITLE
Waveform clipping

### ISSUE THREAD

**Issue by freq-mod** [Wohlstand/libOPNMIDI#73]
YM2612's built-in DAC has a hilariously shitty dynamic range. If an instrument has more than one carrier operator (algorithms 4-7), and volume is too high, it will be clipped.
https://instaud.io/2Wbi -sine, alg=7, total level of all four operators=18
https://instaud.io/2Wbk - the same instument, total level of all operaors raised to 0. It doesn't sound like sine wave anymore, it was clipped to pseudo-square wave.
It's a normal, intended behaviour. OPN-BE has it. Deflemask has it. Real Mega Drives also have it most likely. It's a problem of YM2612's, YM2608 or any other FM synths is free of that crap.
But libOPNMIDI player seems to "ignore" it. Instruments that are distorted in bank editor play "normally" in opnmidiplay, they're not clipped, they're just louder, no matter what emu core is used. Gens 2.10 doesn't emulate waveform clipping, but MAME and Nuked cores do.

**Comment by papiezak** [comment]
Here you can have distorted organ patch to compare how it sounds between bank editor and opnmidiplay - 
[dist organ.zip](https://github.com/Wohlstand/libOPNMIDI/files/2591862/dist.organ.zip)

**Comment by Wohlstand** [comment]
What about YM3438?

**Comment by papiezak** [comment]
I don't know. Wikipedia article on YM2612 in mention of high-volume distortion cites Japanese YM3438 application manual. There is a better way to check if YM3438 does clip waveform so I will look at it now.

**Comment by papiezak** [comment]
Just need to download RetroArch...

**Comment by papiezak** [comment]
Looks like YM3438 also clips waveforms. Doesn't matter whether ASIC or enhanced, MAME or Nuked.

**Comment by Wohlstand** [comment]
Recently, @jpcima have added Mame OPNA emulator, and yeah, I hear that instruments aren't clipping on high volume levels in comparison to OPN2. Yeah, but the question to @nukeykt, what about real chip?

**Comment by nukeykt** [comment]
Both YM2612 and YM3438 use 9-bit accumulator per channel and thus waveform gets clipped.

**Comment by Wohlstand** [comment]
I meat YM2608 and YM2612/YM3438.

**Comment by jpcima** [comment]
@Wohlstand I found MAME YM2608 to compute its channels with 1 more bit of quantization while I imported the panning code.
`out_fm[ch]>>1` was found where used to be `out_fm[ch]>>0`, so I changed accordingly.

**Comment by Wohlstand** [comment]
About of GENS case, it's obvious it's very outdated and inaccurate, but yeah, we can update it with latest and try to make some fixes on it

**Comment by papiezak** [comment]
Hmm...
0006861 might be a reason for library's behaviour. Volume is divided by 2 to eliminate clipping?

**Comment by Wohlstand** [comment]
> Hmm... 0006861 might be a reason for library's behaviour. Volume is divided by 2 to eliminate clipping?
--

I did this division of final output to prevent common clipping between multiple chips without touching of internal logic which is still be same in a case of per-channel clipping.

**Comment by papiezak** [comment]
While testing VGM converter, I accidentally discovered that when "Win9x" volume model is set in PGEMusplay OPNMIDI settings, waveforms get clipped, just like it's supposed to!
Rest of volume models don't do that, and in case of "Generic/Auto" clipping distortion is barely noticeable. 
Strangely, in VLC plugin all volume models sound the same as "Generic", so the clipping is less pronounced than it should 🤷‍♂

**Comment by Wohlstand** [comment]
> While testing VGM converter, I accidentally discovered that when "Win9x" volume model is set in PGEMusplay OPNMIDI settings, waveforms get clipped, just like it's supposed to!

The reason for that in PGE MusPlay (and MixerX) when you have set music volume, is the 2x factor on music volume which is intended to make music louder and not be too silent, however, with some songs, some GME and ADLMIDI/OPNMIDI songs may get clipped. You can try to reduce the volume level to avoid clipping.

**Comment by papiezak** [comment]
When turning volume down, clipping distortion is still there.
By "clipping" I menat that, with YM2612, when multiple carriers' TL level is close to 0, sine wave will be clipped to square-ish wave - as I described in original post.

**Comment by Wohlstand** [comment]
Oh, that, and yeah, the Win9x volume model does louder volume levels while all others are algorithmic with lower volume. To avoid clipping is need to reduce carrier volume in OPN2-BE to avoid that clipping.

**Comment by papiezak** [comment]
Yet clipping seems to be proper behaviour - see @nukeykt expanations:

>Both YM2612 and YM3438 use 9-bit accumulator per channel and thus waveform gets clipped.

**Comment by freq-mod** [comment]
OK, disegard that, libOPNMIDI behaviour is right, turns out. It's MIDI volume  - only some MIDI use values above 120 that cause clipping.
