### ISSUE TITLE
[Question] Modulation scaling?

### ISSUE THREAD

**Issue by papiezak** [Wohlstand/libOPNMIDI#89]
Just a question, in command-line opnplay:
> -s                Enables scaling of modulator volumes

I know it's a leftover from @Bisqwit's original ADLMIDI, it scales oerator volumes... how? It is completely independent from Brightness, it also scales modulation on percussive instruments, what kind of effect is it? 🤔

**Comment by Wohlstand** [comment]
It means the "brightness" effect will follow the volume/velocity level, but brightness is an independent unit that also affects the sound.
In the case of normal volume, there are carriers only scaled, but modulators are untouched. When this flag is enabled, everything is scaled: both modulators and carriers. Brightness does the scale of modulators only without touching of carriers.

**Comment by papiezak** [comment]
OK I see now. Thanks for response.
