### ISSUE TITLE
wopn files?

### ISSUE THREAD

**Issue by zvezdochiot** [Wohlstand/libOPNMIDI#97]
Install `wopn` files in `/usr/share/sounds/wopn`?

**Comment by Wohlstand** [comment]
Перетащил сюда, потому что это имеет значение больше к самой либе libOPNMIDI, чем к редактору банков

**Comment by Wohlstand** [comment]
Кстати, @zvezdochiot , проверь пожалуйста результат, ты можешь по запросу:
```
cmake -DWITH_EXTRA_BANKS=ON ..
```
(чтобы включить установку доп-банков, кроме основного, который по-умолчанию)

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>cmake -DWITH_EXTRA_BANKS=ON ..

Есть такая опция в `ccmake .`. Результат:

```sh
/usr/share/sounds/wopn$ ls -1
fmmidi-readme.txt
fmmidi.wopn
gems-fmlib-gmize-readme.txt
gems-fmlib-gmize.wopn
gm-old.wopn
gm.wopn
gs-by-papiezak-and-sneakernets-readme.txt
gs-by-papiezak-and-sneakernets.wopn
LINKS.txt
readme.txt
Tomsoft-readme.txt
Tomsoft.wopn
wopn specification.txt
xg.wopn
```
Но:
```sh
/usr/bin$ ls -1
opnmidiplay
```
Не вижу `wopn2hpp`! Как же он попадёт в dev пакет?

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>это имеет значение больше к самой либе libOPNMIDI, чем к редактору банков

Не убедил. Пока для банков пользую opn2bankeditor-data_1.3.1-wheezy_all.deb на базе https://github.com/Wohlstand/OPN2BankEditor , ибо первоисточник.

Но! О чудо.
"Вижу о чудо и прозрение!". "Вижу" как ты создаёшь отдельный реп `wopn-soundfonts`, "вижу" в нём унифицированную коллекцию банков. "Вижу" небольшую конфу `cmake` в результате которой наступает порядок: все `txt` уходят в `/usr/share/doc`, в `/usr/share/sounds/wopn` остаются только `wopn` файлы.
"Вижу" как в https://github.com/Wohlstand/libOPNMIDI и https://github.com/Wohlstand/OPN2BankEditor появляются ссылки на https://github.com/Wohlstand/wopn-soundfonts .
"Выжу" как в https://github.com/Wohlstand/libOPNMIDI удаляются все банки, за исключением дефольтного. "Вижу" как в конфе `cmake` вычищаются все "костыли" и дефольтный банк оставляется только для шиндовс версии, а для линя ставится проверка путей:
```
/usr/share/sounds/wopn/gm.wopn
/usr/local/share/sounds/wopn/gm.wopn
```
"Вижу", что если пути пустые, юзер посылается в https://github.com/Wohlstand/wopn-soundfonts

Короче, "вижу" порядок.

**Comment by Wohlstand** [comment]
@zvezdochiot , 
> Только вот wopn specification.txt во-первых с пробелом, а во-вторых не на месте (должен быть в /usr/share/doc/libOPNMIDI).

Его и на репе надо положить в удобное место

> Не вижу wopn2hpp! Как же он попадёт в dev пакет?

Этот скрипт я изначально создал только для своих нужд: для генерации башки под VLC-плагин и для SDL Mixer X, никогда не думал его выпускать как полноценный компонент, используя для нужд лишь некоторых компонентов... А вообще, такое можно и на Си написать и запхать а utils, а ещё использовать его в cmake-сборке для автогенерации башки для vlc-плагина. Это можно сделать чуть позже.

**Comment by Wohlstand** [comment]
> Не убедил. Пока для банков пользую opn2bankeditor-data_1.3.1-wheezy_all.deb на базе https://github.com/Wohlstand/OPN2BankEditor , ибо первоисточник.

Открою тебе секрет: редактор банков это НЕ первоисточник, если не считать конечно то, что это инструмент создания новых банков, но тут уже источник в другом смысле. Но вот всё, что лежит в Bank_Examples, это не первоисточник, это коллекции, собранные со всех уголков интернета для того, чтобы предоставить сырьё для отладки, а также просто примеры банков и инструментов разных форматов. xg.wopn тут староват, и я его давно не обновлял, его первоисточник это именно libOPNMIDI, для которого, собственно, он и создан.

**Comment by Wohlstand** [comment]
> txt уходят в /usr/share/doc, в /usr/share/sounds/wopn остаются только wopn файлы.

Большая часть текстовиков, идущих вместе с wopn-банками - описания к ним, а вот "wopn specification" вполне заслуживает отдельной папки.

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>Большая часть текстовиков, идущих вместе с wopn-банками - описания к ним

Правильно. И если они пойдут отдельной репой, то им место будет в `/usr/share/doc/репа`, а ни где ни попадя.

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>А вообще, такое можно и на Си написать

Зачем? Keep it simple, stupid!

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>Открою тебе секрет: редактор банков это НЕ первоисточник

Тем более прямо напрашивается отдельная репа. А то концы с концами не сходятся.

**Comment by Wohlstand** [comment]
> txt уходят в /usr/share/doc, в /usr/share/sounds/wopn остаются только wopn файлы.

На Си наоборот проще: никаких зависимостей, работает гарантированно, и код простой. Бэшик это решение на коленке ну чисто для себя, а вот на публику решение должно быть независимым и универсальным, и для всех платформ. Тем более утилита hexdump может отсутствовать, и её ещё надо отдельно доустановить.

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>Тем более утилита hexdump может отсутствовать, и её ещё надо отдельно доустановить.

Так тож благо. В зависимоси пхнул, и у тебя уже вместо одной годноты две!

**Comment by Wohlstand** [comment]
На FreeBSD и на macOS нужны будут костыли, ибо там BSD-sed, и да, ты забыл о других платформах, где внешние утилиты другие 🦊

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>ты забыл о других платформах, где внешние утилиты другие

Да, ты прав. Другие платформы я как dev-like не воспринимаю, только как user-like.

**Comment by Wohlstand** [comment]
FreeBSD, OoenBSD, NetBSD? Лол, это ещё более ядрёные платформы, чем все остальные и очень своеобразные при пользовании 🤪 (найдешь там много отличий от линухов, пока будет что то там исследовать)

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>FreeBSD, OoenBSD, NetBSD?

Я б с удовольствием. Тока места на харде 5G осталось. Не разгуляешься. Даже минимальная вирта не влезет.

**Comment by zvezdochiot** [comment]
Labels: "Need a test"

Я же тестанул. Что не так? Другие платформы надобны? Здесь я пас.

**Comment by Wohlstand** [comment]
Надобны, проект кроссплатформенный, и да, поэтому я и сказал, Сишка будет проще, если это хочешь как настоящую утилиту, и которая была бы универсальной

**Comment by Wohlstand** [comment]
> Я же тестанул. Что не так?

Всё так, а вот утилита wopl2hpp это уже отдельная тема, выходит за рамки этой задачи, которая решена, хотя что не так? Текстовик лишений, надо в doc его запхать, а не вместе с банками

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>надо в doc его запхать, а не вместе с банками

Надо репу отдельную для банков сделать, а не переливать из пустого в порожнее. Ну коли и здесь банки не вписываются, и в редакторе они не родные. Надо с ними что-то решать.

**Comment by Wohlstand** [comment]
> Надо репу отдельную для банков сделать, а не переливать из пустого в порожнее. Ну коли и здесь банки не вписываются, и в редакторе они не родные. Надо с ними что-то решать.

Отдельную репу для банков создавать есть смысл, если только хочется организовать из них большую библиотеку, а тут я кладу лишь немного банков, самый минимум. А что, можно так сделать, чтобы любой желающий мог предложить свой банк в эту мини-библиотеку. Для редактора, как я уже говорил, это "биоматериал" для экспериментов новичков и для отладки, поэтому там они будут лежать, но в разумном минимуме.

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>если только хочется организовать из них большую библиотеку

Фиксую: если только хочется организовать

Или как минимум:
https://github.com/Wohlstand/libOPNMIDI/blob/b091398fe08d1133de4a694a016f10393c683c2b/CMakeLists.txt#L371-L374
изменить на:
```cmake
    install(FILES
            ${WOPN_FILES}
            ${WOPNTXT_FILES}
            DESTINATION "${CMAKE_INSTALL_DATAROOTDIR}/doc/libOPNMIDI/wopn")
```
Не?

**Comment by Wohlstand** [comment]
Освежил, смотри результат! :fox_face: :+1: 
Также я написал на Си wopn2hpp, теперь оно точно будет работать как надо на любой платформе :wink:

**Comment by zvezdochiot** [comment]
https://github.com/Wohlstand/libOPNMIDI/commit/b336084039f569063f387a0d60f37b253d59de2e

**Comment by Wohlstand** [comment]
Оки, теперь осталась одна крохотная вещь - портировать недавние правочки с установкой доков ... в сборку libADLMIDI! (однако, это уже другая задача, эта решена)

Okay, one thing is left is... backport documentation installing part into libADLMIDI
(English especially for @jpcima's understanding)

**Comment by zvezdochiot** [comment]
@Wohlstand сказал:
>в сборку libADLMIDI

Поддерживаю.
